package jp.co.wisdom_technology.model;

import java.util.Date;

public class RestPattern {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rest_pattern.id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rest_pattern.start
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Date start;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rest_pattern.end
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Date end;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rest_pattern.id
	 * @return  the value of rest_pattern.id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rest_pattern.id
	 * @param id  the value for rest_pattern.id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rest_pattern.start
	 * @return  the value of rest_pattern.start
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Date getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rest_pattern.start
	 * @param start  the value for rest_pattern.start
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setStart(Date start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rest_pattern.end
	 * @return  the value of rest_pattern.end
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Date getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rest_pattern.end
	 * @param end  the value for rest_pattern.end
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setEnd(Date end) {
		this.end = end;
	}
}