package jp.co.wisdom_technology.model;

public class StaffRest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff_rest.staff_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff_rest.pattern_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Integer patternId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff_rest.staff_id
	 * @return  the value of staff_rest.staff_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff_rest.staff_id
	 * @param staffId  the value for staff_rest.staff_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff_rest.pattern_id
	 * @return  the value of staff_rest.pattern_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Integer getPatternId() {
		return patternId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff_rest.pattern_id
	 * @param patternId  the value for staff_rest.pattern_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setPatternId(Integer patternId) {
		this.patternId = patternId;
	}
}