package jp.co.wisdom_technology.model;

import java.util.Date;

public class TimeSheet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_sheet.staff_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_sheet.date
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_sheet.start
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Date start;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_sheet.end
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private Date end;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column time_sheet.comment
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_sheet.staff_id
	 * @return  the value of time_sheet.staff_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_sheet.staff_id
	 * @param staffId  the value for time_sheet.staff_id
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_sheet.date
	 * @return  the value of time_sheet.date
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_sheet.date
	 * @param date  the value for time_sheet.date
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_sheet.start
	 * @return  the value of time_sheet.start
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Date getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_sheet.start
	 * @param start  the value for time_sheet.start
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setStart(Date start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_sheet.end
	 * @return  the value of time_sheet.end
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public Date getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_sheet.end
	 * @param end  the value for time_sheet.end
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setEnd(Date end) {
		this.end = end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column time_sheet.comment
	 * @return  the value of time_sheet.comment
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column time_sheet.comment
	 * @param comment  the value for time_sheet.comment
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	public void setComment(String comment) {
		this.comment = comment == null ? null : comment.trim();
	}
}