package jp.co.wisdom_technology.mapper;

import java.util.List;
import jp.co.wisdom_technology.model.Staff;

public interface StaffMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	int insert(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	Staff selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	List<Staff> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	int updateByPrimaryKey(Staff record);
}