package jp.co.wisdom_technology.mapper;

import java.util.Date;
import java.util.List;
import jp.co.wisdom_technology.model.TimeSheet;
import org.apache.ibatis.annotations.Param;

public interface TimeSheetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_sheet
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	int deleteByPrimaryKey(@Param("staffId") Integer staffId, @Param("date") Date date);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_sheet
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	int insert(TimeSheet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_sheet
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	TimeSheet selectByPrimaryKey(@Param("staffId") Integer staffId, @Param("date") Date date);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_sheet
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	List<TimeSheet> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_sheet
	 * @mbg.generated  Fri Apr 03 20:57:54 JST 2020
	 */
	int updateByPrimaryKey(TimeSheet record);
}